# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfunfold" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "876ad257eef5011dcb6866f35d2bef4db751c2f7e056ee3160bbb19173409c62"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3d47f18d8461ada65ce380ba373bc271e889f247e9400d79ae66fa8289199f33"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c462bf4deab3603954337d1e7c6781eb572dac55cc7101741be6cd90666ba1e"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "7698aa89f8dc74322be3d7defd3b9214f61c3f0d09d6c70d86689fb3f3904cf9"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfunfold"
  desc "tfunfold expands Terraform for_each / count into individual resources or modules with moved blocks."
  homepage "https://github.com/winebarrel/tfunfold"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfunfold"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfunfold"]
    end
  end

  # No zap stanza required

end
