# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfunfold" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "7852fff13b2233780b75e4a27601d1d96f656fcdc0e3b5e3970b54bd1adfca43"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b6c6ace43856298a060862f789e557874ab4b772465037f8744b97dc9f74753"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb2f32142321c22fa587a8d15bd8d40ef03122725178c556f605876e7b92e86e"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9a00b96d0f755d913d407902fbb1ac95a304d19e30185bb79a954fd301074cea"
      url "https://github.com/winebarrel/tfunfold/releases/download/v#{version}/tfunfold_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfunfold"
  desc "tfunfold expands Terraform for_each / count into individual resources or modules with moved blocks."
  homepage "https://github.com/winebarrel/tfunfold"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfunfold"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfunfold"]
    end
  end

  # No zap stanza required

end
